data:
  datasets:
  - R2V
  - CubiCasa5k
  extend_lines: true
  flip_probability: 0.5
  image_size: !!python/tuple
  - 256
  - 256
  normalize_coords: true
  use_data_augmentation: true
description: Baseline VectorFloorSeg with ResNet-101 backbone
device: cuda
model:
  backbone: resnet101
  dropout: 0.1
  hidden_dim: 256
  nheads: 8
  num_classes: 2
  num_decoder_layers: 6
  num_encoder_layers: 6
name: baseline_resnet101
seed: 42
training:
  batch_size: 8
  boundary_loss_weight: 0.5
  epochs: 50
  gradient_clip_norm: 1.0
  learning_rate: 0.0001
  momentum: 0.9
  scheduler: cosine
  weight_decay: 0.0001
